### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by xbadal** [octomato/preload_page_view#16]
error keeps on coming for no reason. 

Null check operator used on a null value

please let me know what to do?

**Comment by Quving** [comment]
I am also running into this problem! :)

**Comment by xbadal** [comment]
Just try to switch from flutter stable to flutter beta. it worked for me. @Quving

**Comment by Quving** [comment]
Ah thanks a lot. I also found out using flutter stable tags such as version 1.22.2 works also fine.

**Comment by savs90** [comment]
Duplicate of  #18

**Comment by xbadal** [comment]
> Duplicate of #18

please check date before marking it duplicate. #18 is Duplicate of #16

**Comment by crtl** [comment]
Having the same issue. Seems to be related to [https://github.com/flutter/flutter/issues/66250](https://github.com/flutter/flutter/issues/66250)

**Comment by crtl** [comment]
savs90 provided a fix in https://github.com/octomato/preload_page_view/issues/18.
Ive implemented in a new fork which is available with:
```
preload_page_view:
    git:
      url: "https://github.com/crtl/preload_page_view.git"
      ref: "fix-null-check-operators"
```
